Text = "ACCATCCATCCTAATAGAAAGATACGGGTCAAGGTCGCCTAATAGAACCATCCATGTCAAGGTCGACCATCCATGTCAAGGTCGACCATCCATGTCAAGGTCGAAGATACGGAAGATACGGACCATCCATGTCAAGGTCGGTCAAGGTCGCGGAGTCTCCGGAGTCTCCCTAATAGAAAGATACGGCGGAGTCTCACCATCCATAAGATACGGAAGATACGGACCATCCATACCATCCATCGGAGTCTCACCATCCATAAGATACGGCCTAATAGAACCATCCATCGGAGTCTCACCATCCATAAGATACGGCCTAATAGACCTAATAGAAAGATACGGAAGATACGGCGGAGTCTCACCATCCATCCTAATAGAGTCAAGGTCGCGGAGTCTCCCTAATAGAAAGATACGGCGGAGTCTCCCTAATAGAGTCAAGGTCGCGGAGTCTCGTCAAGGTCGCGGAGTCTCCGGAGTCTCGTCAAGGTCGCCTAATAGAACCATCCATCCTAATAGAAAGATACGGAAGATACGGCGGAGTCTCACCATCCATCCTAATAGACGGAGTCTCACCATCCATCGGAGTCTCACCATCCATACCATCCATACCATCCATACCATCCATAAGATACGGCGGAGTCTCGTCAAGGTCGCGGAGTCTCAAGATACGGGTCAAGGTCGACCATCCATCCTAATAGAAAGATACGGCGGAGTCTCAAGATACGGCCTAATAGAAAGATACGGACCATCCATCCTAATAGACGGAGTCTCGTCAAGGTCGACCATCCATCGGAGTCTCACCATCCATCGGAGTCTCCGGAGTCTCAAGATACGGAAGATACGGAAGATACGGAAGATACGGCCTAATAGAGTCAAGGTCGCGGAGTCTCGTCAAGGTCGAAGATACGGCGGAGTCTCAAGATACGG"
n=14
def Najk(text, k):
    skup=[]
    skupsvih=[]
    nizd=[]
    for i in range(len(text)-k):
      skupsvih.append(text[i : i+k])
      nizd.append(0)
    for i in range(len(skupsvih)):
      nizd[i]=Count(text,text[i : i+k])

    M=max(nizd)
    print(M)
    for i in range(len(skupsvih)):
      if(M==nizd[i]):
        if(skupsvih[i] not in skup):
          skup.append(skupsvih[i])

    return skup

print(Najk(Text, n))
