# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zhbs48Ci21P01arwdn387U0lZj5CIAje
"""

pattern="ACTG"
def revcom(pattern):
  rj=""
  for i in range(len(pattern)-1,-1,-1):
    if(pattern[i]=="A"):
      rj+="T"
    elif(pattern[i]=="C"):
      rj+="G"
    elif(pattern[i]=="G"):
      rj+="C"
    elif(pattern[i]=="T"):
      rj+="A"
  return rj

print(revcom(pattern))