# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LTW7X_XPIBhYMfys4Hr6sSy3w0aJ1KV5
"""

from google.colab import drive
drive.mount('/content/drive')

# 3 B

f = open("/content/rosalind_ba3b (4).txt", "r")
patterns = f.read().splitlines()
print(len(patterns))
patterns=list(patterns)
k=len(patterns[0])
st=patterns[0]
for i in range(1,len(patterns)):
  st+=patterns[i][k-1]
print(st)