# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rSR__qiC3Ec77yzIdpPQ3RL7qOAtPMfF
"""

input=open("/content/rosalind_ba6b.txt","r")

def SyntenyToList(s):
    l = []
    j = 1
    for i in range(0, len(s)):
        if(s[i] == " " or s[i] == ")"):
            l.append(int(s[j:i]))
            j = i + 1
    return l

def Breakpoints(lsynteny):
    if(lsynteny[0] != 1):
        b = 1
    else:
        b = 0
    for i in range(len(lsynteny) - 1):
        if(lsynteny[i] + 1 != lsynteny[i + 1]):
            b += 1
    return b

print(Breakpoints(SyntenyToList(input.read())))