# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LTW7X_XPIBhYMfys4Hr6sSy3w0aJ1KV5
"""

from google.colab import drive
drive.mount('/content/drive')

def chromosomeToCycle(chromosome):
    chromosome = chromosome[1:].split(" ")
    chromosome = [int(x) for x in chromosome]
    absChromosome = [abs(x) for x in chromosome]
    minC = min(absChromosome)
    nodes = [i for i in range(2*minC - 1, 2*len(chromosome) + 2*minC - 1)]
    for j in range(0, len(chromosome)):
        i = chromosome[j]
        if(i < 0):
            temp = nodes[2*j]
            nodes[2*j] = nodes[2*j + 1]
            nodes[2*j + 1] = temp
    return nodes

def coloredEdges(chrs):
    edges = []
    for chr in chrs:
        nodes = chromosomeToCycle(chr)
        for j in range(1, len(nodes)//2):
            edges.append([nodes[2*j - 1], nodes[2*j]])
        edges.append([nodes[-1], nodes[0]])
    return edges

chrs = "(+1 +2 +3 +4 -5 -6 +7 +8 -9 +10 +11 +12 -13 -14 -15 +16 -17 +18 -19 +20 -21 -22 -23 -24 -25 -26 +27 -28 -29)(+30 -31 +32 +33 +34 -35 +36 +37 -38 +39 -40 +41 +42 +43 +44 +45 -46 +47 -48 +49 +50 +51 +52 +53 -54 -55 -56 -57 +58 +59)(+60 -61 +62 +63 -64 -65 +66 -67 +68 -69 -70 +71 -72 +73 -74 +75 +76 -77 -78 +79 -80 +81 +82 -83 +84 -85 -86 +87 -88)(+89 +90 -91 +92 -93 -94 +95 +96 -97 -98 +99 +100 +101 -102 -103 -104 -105 +106 -107 +108 +109)(-110 +111 -112 +113 -114 +115 -116 +117 +118 +119 -120 -121 +122 -123 -124 -125 -126 +127 -128 -129 -130 +131 +132 -133 -134 +135 +136 -137 -138)(-139 +140 +141 -142 -143 +144 +145 +146 -147 +148 +149 -150 -151 +152 +153 +154 +155 -156 +157 -158 -159 +160 +161 -162 +163 -164)(-165 -166 -167 -168 +169 +170 +171 -172 -173 -174 -175 +176 +177 +178 +179 +180 +181 -182 -183 -184 +185 +186 -187 +188 +189)(+190 +191 -192 -193 -194 +195 +196 -197 +198 +199 +200 -201 -202 +203 +204 -205 -206 -207 +208 +209 +210 -211 -212 +213 +214"
#ne zaboravi u unosu izbrisat zadnju zagradu
chrs = chrs.split(")")
pr = ""
print(coloredEdges(chrs))
for i in coloredEdges(chrs):
    pr += "(" + str(i[0]) + ", " + str(i[1]) + "), "
print(pr)